const sampleListings = [
  {
    title: "Cozy Beachfront Cottage",
    description: "Escape to this charming beachfront cottage for a relaxing getaway. Enjoy stunning ocean views and easy access to the beach.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?auto=format&fit=crop&w=800&q=60" },
    price: 1500, location: "Malibu", country: "United States", category: "Trending",
  },
  {
    title: "Modern Loft in Downtown",
    description: "Stay in the heart of the city in this stylish loft apartment. Perfect for urban explorers!",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60" },
    price: 1200, location: "New York City", country: "United States", category: "City",
  },
  {
    title: "Mountain Retreat",
    description: "Unplug and unwind in this peaceful mountain cabin. Surrounded by nature, it's a perfect place to recharge.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=60" },
    price: 1000, location: "Aspen", country: "United States", category: "Mountains",
  },
  {
    title: "Historic Villa in Tuscany",
    description: "Experience the charm of Tuscany in this beautifully restored villa. Explore the rolling hills and vineyards.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=60" },
    price: 2500, location: "Florence", country: "Italy", category: "Trending",
  },
  {
    title: "Secluded Treehouse Getaway",
    description: "Live among the treetops in this unique treehouse retreat. A true nature lover's paradise.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=800&q=60" },
    price: 800, location: "Portland", country: "United States", category: "Trending",
  },
  {
    title: "Beachfront Paradise",
    description: "Step out of your door onto the sandy beach. This beachfront condo offers the ultimate relaxation.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?auto=format&fit=crop&w=800&q=60" },
    price: 2000, location: "Cancun", country: "Mexico", category: "Trending",
  },
  {
    title: "Rustic Cabin by the Lake",
    description: "Spend your days fishing and kayaking on the serene lake. This cozy cabin is perfect for outdoor enthusiasts.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=60" },
    price: 900, location: "Lake Tahoe", country: "United States", category: "Camping",
  },
  {
    title: "Luxury Penthouse with City Views",
    description: "Indulge in luxury living with panoramic city views from this stunning penthouse apartment.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1622396481328-9b1b78cdd9fd?auto=format&fit=crop&w=800&q=60" },
    price: 3500, location: "Los Angeles", country: "United States", category: "City",
  },
  {
    title: "Ski-In/Ski-Out Chalet",
    description: "Hit the slopes right from your doorstep in this ski-in/ski-out chalet in the Swiss Alps.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?auto=format&fit=crop&w=800&q=60" },
    price: 3000, location: "Verbier", country: "Switzerland", category: "Mountains",
  },
  {
    title: "Safari Lodge in the Serengeti",
    description: "Experience the thrill of the wild in a comfortable safari lodge. Witness the Great Migration up close.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?auto=format&fit=crop&w=800&q=60" },
    price: 4000, location: "Serengeti National Park", country: "Tanzania", category: "Trending",
  },
  {
    title: "Historic Canal House",
    description: "Stay in a piece of history in this beautifully preserved canal house in Amsterdam's iconic district.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=800&q=60" },
    price: 1800, location: "Amsterdam", country: "Netherlands", category: "City",
  },
  {
    title: "Private Island Retreat",
    description: "Have an entire island to yourself for a truly exclusive and unforgettable vacation experience.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1618140052121-39fc6db33972?auto=format&fit=crop&w=800&q=60" },
    price: 10000, location: "Fiji", country: "Fiji", category: "Trending",
  },
  {
    title: "Charming Cottage in the Cotswolds",
    description: "Escape to the picturesque Cotswolds in this quaint and charming cottage with a thatched roof.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1602088113235-229c19758e9f?auto=format&fit=crop&w=800&q=60" },
    price: 1200, location: "Cotswolds", country: "United Kingdom", category: "Rooms",
  },
  {
    title: "Historic Brownstone in Boston",
    description: "Step back in time in this elegant historic brownstone located in the heart of Boston.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1533619239233-6280475a633a?auto=format&fit=crop&w=800&q=60" },
    price: 2200, location: "Boston", country: "United States", category: "City",
  },
  {
    title: "Beachfront Bungalow in Bali",
    description: "Relax on the sandy shores of Bali in this beautiful beachfront bungalow with a private pool.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1602391833977-358a52198938?auto=format&fit=crop&w=800&q=60" },
    price: 1800, location: "Bali", country: "Indonesia", category: "Amazing Pool",
  },
  {
    title: "Mountain View Cabin in Banff",
    description: "Enjoy breathtaking mountain views from this cozy cabin in the Canadian Rockies.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1521401830884-6c03c1c87ebb?auto=format&fit=crop&w=800&q=60" },
    price: 1500, location: "Banff", country: "Canada", category: "Mountains",
  },
  {
    title: "Art Deco Apartment in Miami",
    description: "Step into the glamour of the 1920s in this stylish Art Deco apartment in South Beach.",
    image: { filename: "listingimage", url: "https://plus.unsplash.com/premium_photo-1670963964797-942df1804579?auto=format&fit=crop&w=800&q=60" },
    price: 1600, location: "Miami", country: "United States", category: "City",
  },
  {
    title: "Tropical Villa in Phuket",
    description: "Escape to a tropical paradise in this luxurious villa with a private infinity pool in Phuket.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1470165301023-58dab8118cc9?auto=format&fit=crop&w=800&q=60" },
    price: 3000, location: "Phuket", country: "Thailand", category: "Amazing Pool",
  },
  {
    title: "Historic Castle in Scotland",
    description: "Live like royalty in this historic castle in the Scottish Highlands. Explore the rugged beauty of the area.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1585543805890-6051f7829f98?auto=format&fit=crop&w=800&q=60" },
    price: 4000, location: "Scottish Highlands", country: "United Kingdom", category: "Castles",
  },
  {
    title: "Desert Oasis in Dubai",
    description: "Experience luxury in the middle of the desert in this opulent oasis in Dubai with a private pool.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=800&q=60" },
    price: 5000, location: "Dubai", country: "United Arab Emirates", category: "Amazing Pool",
  },
  {
    title: "Rustic Log Cabin in Montana",
    description: "Unplug and unwind in this cozy log cabin surrounded by the natural beauty of Montana.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1586375300773-8384e3e4916f?auto=format&fit=crop&w=800&q=60" },
    price: 1100, location: "Montana", country: "United States", category: "Camping",
  },
  {
    title: "Beachfront Villa in Greece",
    description: "Enjoy the crystal-clear waters of the Mediterranean in this beautiful beachfront villa on a Greek island.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?auto=format&fit=crop&w=800&q=60" },
    price: 2500, location: "Mykonos", country: "Greece", category: "Trending",
  },
  {
    title: "Eco-Friendly Treehouse Retreat",
    description: "Stay in an eco-friendly treehouse nestled in the forest. It's the perfect escape for nature lovers.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1488462237308-ecaa28b729d7?auto=format&fit=crop&w=800&q=60" },
    price: 750, location: "Costa Rica", country: "Costa Rica", category: "Camping",
  },
  {
    title: "Historic Cottage in Charleston",
    description: "Experience the charm of historic Charleston in this beautifully restored cottage with a private garden.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1587381420270-3e1a5b9e6904?auto=format&fit=crop&w=800&q=60" },
    price: 1600, location: "Charleston", country: "United States", category: "Rooms",
  },
  {
    title: "Modern Apartment in Tokyo",
    description: "Explore the vibrant city of Tokyo from this modern and centrally located apartment.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1480796927426-f609979314bd?auto=format&fit=crop&w=800&q=60" },
    price: 2000, location: "Tokyo", country: "Japan", category: "City",
  },
  {
    title: "Lakefront Cabin in New Hampshire",
    description: "Spend your days by the lake in this cozy cabin in the scenic White Mountains of New Hampshire.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1578645510447-e20b4311e3ce?auto=format&fit=crop&w=800&q=60" },
    price: 1200, location: "New Hampshire", country: "United States", category: "Camping",
  },
  {
    title: "Luxury Villa in the Maldives",
    description: "Indulge in luxury in this overwater villa in the Maldives with stunning views of the Indian Ocean.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=800&q=60" },
    price: 6000, location: "Maldives", country: "Maldives", category: "Amazing Pool",
  },
  {
    title: "Ski Chalet in Aspen",
    description: "Hit the slopes in style with this luxurious ski chalet in the world-famous Aspen ski resort.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=800&q=60" },
    price: 4000, location: "Aspen", country: "United States", category: "Mountains",
  },
  {
    title: "Secluded Beach House in Costa Rica",
    description: "Escape to a secluded beach house on the Pacific coast of Costa Rica. Surf, relax, and unwind.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&w=800&q=60" },
    price: 1800, location: "Costa Rica", country: "Costa Rica", category: "Trending",
  },
  {
    title: "Beach House in Goa",
    description: "Enjoy a relaxing stay near the beach with beautiful sunsets.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60" },
    price: 3500, location: "Goa", country: "India", category: "Trending",
  },
  {
    title: "Mountain Cabin in Manali",
    description: "Cozy wooden cabin with breathtaking mountain views.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60" },
    price: 2500, location: "Manali", country: "India", category: "Mountains",
  },
  {
    title: "Apartment in New York",
    description: "Modern apartment in the heart of the city.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=800&q=60" },
    price: 8000, location: "New York", country: "USA", category: "City",
  },
  {
    title: "Desert Camp in Rajasthan",
    description: "Experience royal desert life with cultural nights.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=800&q=60" },
    price: 2000, location: "Jaisalmer", country: "India", category: "Camping",
  },
  {
    title: "Lake House in Switzerland",
    description: "Peaceful house beside a scenic lake.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=60" },
    price: 9000, location: "Zurich", country: "Switzerland", category: "Rooms",
  },
  {
    title: "Studio Apartment in Tokyo",
    description: "Compact and modern studio in Tokyo city.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=800&q=60" },
    price: 7000, location: "Tokyo", country: "Japan", category: "Rooms",
  },
  {
    title: "Treehouse in Kerala",
    description: "Stay close to nature in a beautiful treehouse.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1502082553048-f009c37129b9?auto=format&fit=crop&w=800&q=60" },
    price: 3000, location: "Kerala", country: "India", category: "Camping",
  },
  // New 15 listings for remaining categories
  {
    title: "Medieval Castle in France",
    description: "Stay in a stunning medieval castle with towers, moats and royal interiors in the Loire Valley.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1543429258-a5c9e634e06f?auto=format&fit=crop&w=800&q=60" },
    price: 5500, location: "Loire Valley", country: "France", category: "Castles",
  },
  {
    title: "Castle Stay in Prague",
    description: "Experience living in a real European castle overlooking the city of Prague.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1562184552-997c461abbe6?auto=format&fit=crop&w=800&q=60" },
    price: 4500, location: "Prague", country: "Czech Republic", category: "Castles",
  },
  {
    title: "Pool Villa in Santorini",
    description: "Breathtaking infinity pool overlooking the Aegean Sea in iconic Santorini.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?auto=format&fit=crop&w=800&q=60" },
    price: 6000, location: "Santorini", country: "Greece", category: "Amazing Pool",
  },
  {
    title: "Arctic Glass Igloo in Finland",
    description: "Sleep under the northern lights in a stunning glass igloo in Lapland Finland.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?auto=format&fit=crop&w=800&q=60" },
    price: 7000, location: "Lapland", country: "Finland", category: "Arctic",
  },
  {
    title: "Ice Hotel in Norway",
    description: "A once in a lifetime experience sleeping in a hotel made entirely of ice and snow.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1520769945061-0a448c463865?auto=format&fit=crop&w=800&q=60" },
    price: 8000, location: "Tromsø", country: "Norway", category: "Arctic",
  },
  {
    title: "Aurora Cabin in Iceland",
    description: "Watch the northern lights from your cozy cabin in the Icelandic wilderness.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1504893524553-b855bce32c67?auto=format&fit=crop&w=800&q=60" },
    price: 5000, location: "Reykjavik", country: "Iceland", category: "Arctic",
  },
  {
    title: "Organic Farm Stay in Tuscany",
    description: "Wake up to fresh air and farm life in this beautiful organic farm in the Tuscan countryside.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=800&q=60" },
    price: 1800, location: "Tuscany", country: "Italy", category: "Farms",
  },
  {
    title: "Farm Cottage in New Zealand",
    description: "Experience authentic farm life surrounded by rolling green hills in New Zealand.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=60" },
    price: 2200, location: "Queenstown", country: "New Zealand", category: "Farms",
  },
  {
    title: "Lavender Farm in Provence",
    description: "Stay on a working lavender farm and enjoy the stunning purple fields of Provence.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1499002238440-d264edd596ec?auto=format&fit=crop&w=800&q=60" },
    price: 2800, location: "Provence", country: "France", category: "Farms",
  },
  {
    title: "Cozy Room in Paris",
    description: "A charming private room in a classic Parisian apartment near the Eiffel Tower.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=800&q=60" },
    price: 2500, location: "Paris", country: "France", category: "Rooms",
  },
  {
    title: "Private Room in Barcelona",
    description: "Stylish private room in a shared apartment in the heart of Barcelona.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1539037116277-4db20889f2d4?auto=format&fit=crop&w=800&q=60" },
    price: 1800, location: "Barcelona", country: "Spain", category: "Rooms",
  },
  {
    title: "City Center Room in London",
    description: "Affordable private room with easy access to all major London attractions.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1486325212027-8081e485255e?auto=format&fit=crop&w=800&q=60" },
    price: 3000, location: "London", country: "United Kingdom", category: "Rooms",
  },
];

module.exports = { data: sampleListings };